services:
  web-server:
    build: ./web-server
    image: web-server:latest
    container_name: web-server
    hostname: web-server
    ports:
      - 80:80
    depends_on:
      api-server:
        condition: service_healthy

  api-server:
    build: ./api-server
    image: api-server:latest
    container_name: api-server
    hostname: api-server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15.12-alpine3.21
    container_name: database
    hostname: database
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      # - ./volumes/postgres:/var/lib/postgresql/data
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1s
      interval: 30s
      timeout: 3s
      retries: 5
    # ports:
    #   - 5432:5432

volumes:
  data:
    name: database_data

networks:
  default:
    name: my_network
